version: "3.8"

services:
    $APP_NAME_app:
        build:
            context: ./app
        working_dir: /app
        volumes:
            - ./app:/app

    $APP_NAME_nginx:
        build:
            context: ./nginx
        depends_on:
            - $APP_NAME_app
        volumes:
            - ./app:/app
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d

    $APP_NAME_node:
        image: node:12-alpine
        working_dir: /app
        volumes:
            - ./app:/app
        command: yarn docker:prod
